@startdot record
digraph servoStates {
  graph [ dpi = 300 ];
  node[shape=record style="rounded"];
  off [label="{off | {{motionDetected|false} | {servoInProgress|false} | {startServo|false}}}"];
  motionDetected [label="{motionDetected | {{motionDetected|true} | {servoInProgress|false} | {startServo|false}}}"];
  starting [label="{starting | {{motionDetected|X} | {servoInProgress|X} | {startServo|true}}}"];
  running [label="{running | {{motionDetected|true} | {servoInProgress|true} | {startServo|false}}}"];
  servoStopping [label="{servoStopping | {{motionDetected|false} | {servoInProgress|true} | {startServo|false}}}"];
  node [shape = point ]; start

  start -> starting;
  off -> motionDetected [label="sensor triggered" style=dotted];
  motionDetected -> starting;
  starting -> running;
  running -> servoStopping [label="trigger expired" style=dotted];
  starting -> servoStopping;
  servoStopping -> off;
}
@enddot
@startdot graph
digraph servoStates {
  rankdir=LR
  compound=true;
  graph [ dpi = 300 ];

  node [shape = doublecircle] config;
  node [shape = point ]; start
  node[shape=record style=rounded];

  subgraph cluster0 {
    label="On"
    shape=record
    style=rounded
    starting [label="starting | entry/ update servo position"];
    running;

    node [shape=point]; onInit;
    onInit -> starting;

    starting -> running;
  }

  subgraph cluster1 {
    label="Off"
    shape=record
    style=rounded
    motionDetected [label="motionDetected | exit/ determine next angle"]
    servoStopping -> off;
    off -> motionDetected [label="sensor triggered" style=dotted];
    offInit [shape=point]
    offInit -> servoStopping;
  }

  start -> starting [label="application start" lhead=cluster0];

  running -> off [label="trigger expired" style=dotted lhead=cluster1]
  config -> starting [label="angle updated\nfrom config" lhead=cluster0];
  motionDetected -> starting [lhead=cluster0];
}
@enddot